import json
import sys
from dataclasses import dataclass
from typing import (
    Literal,
    NotRequired,
    TextIO,
    TypeAlias,
    TypedDict,
    assert_never,
    cast,
)

import numpy as np
from PIL import Image

BYTE_DTYPE = np.uint8
BYTE_SIZE = np.dtype(BYTE_DTYPE).itemsize * 8

class Element(TypedDict):
    draw_color: NotRequired[int]
    x: int
    y: int

class Asset(Element):
    type: Literal["asset"]
    name: str
    time: NotRequired[int]
    offset: NotRequired[int]
    bitmap_mode: NotRequired[int]

class Text(Element):
    type: Literal["text"]
    font: NotRequired[int]
    font_mode: NotRequired[int]
    text: str

class Rectangle(Element):
    type: Literal["rectangle"]
    width: int
    height: int
    filled: NotRequired[bool]

class Custom(TypedDict):
    type: Literal["custom"]
    name: str

ElementType: TypeAlias = Asset | Text | Rectangle | Custom
Elements: TypeAlias = list[ElementType]

class Data(TypedDict):
    assets: dict[str, list[str]] | dict[str, str]
    scenes: dict[str, Elements] | list[str]

@dataclass
class Sprite:
    width: int
    height: int

@dataclass
class AnimatedSprite(Sprite):
    count: int

@dataclass
class StaticSprite(Sprite):
    ...

asset_map: dict[str, Sprite] = {}

def write_bytes(out: TextIO, image: Image.Image, indent: int):
    pixels = np.asarray(image.convert("1"), dtype=BYTE_DTYPE)
    _, width = map(int, pixels.shape)

    padded_width = (width + BYTE_SIZE - 1) // BYTE_SIZE * BYTE_SIZE

    if padded_width != width:
        pixels = np.pad(pixels,((0, 0), (0, padded_width - width)))

    data = np.ravel(np.packbits(pixels, axis=1, bitorder="little"))

    prefix = " " * indent;
    values = "".join(f"\\{x:03o}" for x in data)
    _ = out.write(f"{prefix}\"{values}\"")


def write_static(out: TextIO, name: str, path: str):
    with Image.open(path) as image:
        _ = out.write(f"constexpr Sprite<{image.width}, {image.height}, 1> {name} PROGMEM = {{\n")
        write_bytes(out, image, 4)
        _ = out.write("\n};\n\n")
        asset_map[name] = StaticSprite(image.width, image.height)


def write_animated(out: TextIO, name: str, paths: list[str]):
    images = [Image.open(path) for path in paths];
    _ = out.write(f"constexpr Sprite<{images[0].width}, {images[0].height}, {len(images)}> {name} PROGMEM = {{\n")

    for i, image in enumerate(images):
        write_bytes(out, image, 4);
        if i + 1 < len(images):
            _ = out.write(",\n")

    _ = out.write("\n};\n\n")

    asset_map[name] = AnimatedSprite(images[0].width, images[0].height, len(images))

    for image in images:
        image.close()


def cpp_constructor(name: str, *args: object) -> str:
    return f"{name}({', '.join(map(str, args))})"


def element_expression(element: ElementType) -> str:
    if element["type"] == "custom":
        return element["name"];

    x = element["x"]
    y = element["y"]
    draw_color: int = element.get("draw_color", 1)
    match element["type"]:
        case "asset":
            name = element["name"]
            assert name in asset_map, f"asset {name} not defined in asset map!"
            bitmap_mode: int = element.get("bitmap_mode", 0)
            if isinstance(asset_map[name], AnimatedSprite):
                return cpp_constructor("element::AnimatedSprite", f"graphics::{name}", bitmap_mode, element.get("time", 300), element.get("offset", 0), x, y, draw_color)
            else:
                return cpp_constructor("element::StaticSprite", f"graphics::{name}", bitmap_mode, x, y, draw_color)
        case "text":
            return cpp_constructor("element::Text", element.get("font", "u8g2_font_t0_14_mf"), f"\"{element["text"]}\"", element.get("font_mode", 0), x, y, draw_color)
        case "rectangle":
            return cpp_constructor("element::Rectangle", element["width"], element["height"], "true" if element.get("filled", True) else "false", x, y, draw_color)
        case _:
            assert_never(element["type"])


def write_element(out: TextIO, element: ElementType, indent: int):
    prefix = " " * indent;
    expression = element_expression(element)
    _ = out.write(prefix + expression)


def write_complex_scene(out: TextIO, name: str, elements: Elements):
    _ = out.write(f"inline Scene {name} = {{\n")
    for i, element in enumerate(elements):
        write_element(out, element, 4);
        if i + 1 < len(elements):
            _ = out.write(",\n")
    _ = out.write("\n};\n\n")

def write_simple_scene(out: TextIO, name: str):
    _ = out.write(f"constexpr Scene {name}_scene = {{\n");

    element: Asset = {
        "type": "asset",
        "name": name,
        "x": 0,
        "y": 0,
    };

    write_element(out, element, 4);
    _ = out.write("\n};\n\n");

def main():
    with open(sys.argv[2], "w") as out, open(sys.argv[1], "r") as file:
        _ = out.write("""\
// GENERATED BY 'generate_graphics.py' SCRIPT IN '/tools/'
#pragma once

#include "scene.hpp"
#include "custom.hpp"

namespace graphics {

"""
        );

        data = cast(Data, json.load(file));
        assets = data["assets"];
        scenes = data["scenes"];

        for (name, value) in assets.items():
            assert name not in asset_map, f"asset {name} already exists!"
            if isinstance(value, list):
                write_animated(out, name, value);
            else:
                write_static(out, name, value);

        if isinstance(scenes, list):
            for scene in scenes:
                write_simple_scene(out, scene);
        else:
            for (name, scene) in scenes.items():
                write_complex_scene(out, name, scene);

        _ = out.write("""\
} // namespace graphics
"""
        );

        print(f"outputted cpp header from '{sys.argv[1]}' at '{sys.argv[2]}'");

if __name__ == "__main__":
    main()
