import json
import sys

import numpy as np
from PIL import Image

def write_bytes(image, indent):
    data = np.frombuffer(image.convert("1").tobytes(), dtype=np.uint8);
    data = np.unpackbits(data).reshape(-1, 8)[:, ::-1];
    data = np.packbits(data);
    length = image.width // 8;
    for row in range(image.height):
        start = row * length;
        end = start + length;
        row_data = data[start:end];
        out.write(" " * indent);
        out.write(", ".join(f"0x{x:02x}" for x in row_data));
        if row < image.height - 1:
            out.write(",\n");


def write_image(name, path):
    with Image.open(path) as image:
        out.write(f"constexpr Sprite<{image.width}, {image.height}, 1> {name} PROGMEM = {{\n    {{\n");
        write_bytes(image, 8);
        out.write("\n    }\n};\n\n");


def write_animation(name, paths):
    images = [Image.open(path) for path in paths];
    out.write(f"constexpr Sprite<{images[0].width}, {images[0].height}, {len(images)}> {name} PROGMEM = {{\n    {{\n        {{\n");
    for image in images[:-1]:
        write_bytes(image, 12);
        out.write("\n        },\n        {\n");
    write_bytes(images[-1], 12);
    out.write("\n        }\n    }\n};\n\n");
    for image in images:
        image.close();


def write_element(name, data, indent):
    print(data);
    out.write(" " * indent);
    if "text" in data:
        out.write(f"TextElement({data["font"]}, \"{data["text"]}\", {data["x"]}, {data["y"]})");
    elif "time" in data:
        out.write(f"AnimatedElement(Graphics::{name}, {data["x"]}, {data["y"]}, {data["time"]})");
    else:
        out.write(f"StaticElement(Graphics::{name}, {data["x"]}, {data["y"]})");


def write_complex_scene(name, elements):
    out.write(f"constexpr Scene {name}{{\n");
    for key in list(elements.keys())[:-1]:
        write_element(key, elements[key], 4);
        out.write(",\n");
    last = list(elements.keys())[-1];
    write_element(last, elements[last], 4);
    out.write("\n};\n\n");

def write_simple_scene(name):
    out.write(f"constexpr Scene {name}_scene{{\n");
    data = {
        "x": 0,
        "y": 0,
    };
    write_element(name, data, 4);
    out.write("\n};\n\n");


out = open(sys.argv[2], "w");

out.write("""
// GENERATED BY 'to_asset.py' SCRIPT IN '/tools/to_graphics.py'
#pragma once

#include "scene.hpp"

namespace Graphics {

""");


with open(sys.argv[1], "r") as file:
    data = json.load(file);
    assets = data["assets"];
    scenes = data["scenes"];
    for key in assets.keys():
        value = assets[key];
        if isinstance(value, list):
            write_animation(key, value);
        else:
            write_image(key, value);
    if isinstance(scenes, list):
        for scene in scenes:
            write_simple_scene(scene);
    else:
        for key in scenes.keys():
            write_complex_scene(key, scenes[key]);


out.write("} // end namespace Graphics\n");


out.close();
