from PIL import Image
import numpy as np
import sys
import json

def write_bytes(image, indent):
    data = np.frombuffer(image.convert("1").tobytes(), dtype=np.uint8);
    data = np.unpackbits(data).reshape(-1, 8)[:, ::-1];
    data = np.packbits(data);
    length = image.width // 8;
    for row in range(image.height):
        start = row * length;
        end = start + length;
        row_data = data[start:end];
        out.write(" " * indent);
        out.write(", ".join(f"0x{x:02x}" for x in row_data));
        if row < image.height - 1:
            out.write(",\n");


def write_image(name, path):
    with Image.open(path) as image:
        out.write(f"constexpr Image<{image.width}, {image.height}> {name} PROGMEM = {{\n    {{\n");
        write_bytes(image, 8);
        out.write("\n    }\n};\n\n");


def write_animation(name, paths):
    images = [Image.open(path) for path in paths];
    out.write(f"constexpr Animation<{images[0].width}, {images[0].height}, {len(images)}> {name} PROGMEM = {{\n    {{\n        {{\n");
    for image in images[:-1]:
        write_bytes(image, 12);
        out.write("\n        },\n        {\n");
    write_bytes(images[-1], 12);
    out.write("\n        }\n    }\n};\n\n");
    for image in images:
        image.close();


out = open(sys.argv[2], "w");


out.write("""
// GENERATED BY 'to_asset.py' SCRIPT IN '/tools/to_graphics.py'
#pragma once

#include <Arduino.h>
#include <U8g2lib.h>

#define BYTE_SIZE 8

namespace Graphics {

template <size_t Width, size_t Height, size_t N>
struct Animation {
    static constexpr size_t width = Width;
    static constexpr size_t height = Height;
    static constexpr size_t count = N;
    uint8_t frames[N][Width * Height / BYTE_SIZE];
};

template <size_t Width, size_t Height>
struct Image {
    static constexpr u8g2_uint_t width = Width;
    static constexpr u8g2_uint_t height = Height;
    uint8_t bitmap[Width * Height / BYTE_SIZE];
};

""");


with open(sys.argv[1], "r") as file:
    data = json.load(file);
    for key in data.keys():
        value = data[key];
        if isinstance(value, list):
            write_animation(key, value);
        else:
            write_image(key, value);


out.write("} // end namespace Graphics\n");


out.close();
